name             'op-collectd'
maintainer       'Sammy'
maintainer_email 'sammylintw@gmail.com'
license          'All rights reserved'
description      'Installs/Configures op-collectd'
long_description 'Installs/Configures op-collectd'
version          '0.1.0'